//action type
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const RESETPASSWORD = "RESETPASSWORD";
// export const SUPPORT_CREATE="SUPPORT_CREATE";




//SERVER RESPONSE AGANIST CERTAIN ACTIVITY
export const SUPPORT_RESP="SUPPORT_RESP";
export const REGISTER_RESP="REGISTER_RESP";
export const LOGIN_RESP="LOGIN_RESP";


export const USER_FIELDMODE_SAVE_RESP="USER_FIELDMODE_SAVE_RESP";
export const USER_FIELDMODE_FETCH_RESP="USER_FIELDMODE_SAVE_RESP";
export const USER_FIELDMODE_DELETE_RESP="USER_FIELDMODE_SAVE_RESP";

export const PROJECT_DETAILS_FETCH_RESP="PROJECT_DETAILS_FETCH_RESP";
export const PROJECT_DETAILS_POST_RESP="PROJECT_DETAILS_POST_RESP";
export const PROJECT_DETAILS_DELETE_RESP="PROJECT_DETAILS_DELETE_RESP";

export const  GET_EXISTING_PROJECT_RESP="GET_EXISTING_PROJECT_RESP";


export const PROJECT_BRIEF_FETCH_RESP="PROJECT_BRIEF_FETCH_RESP";
export const PROJECT_BRIEF_POST_RESP="PROJECT_BRIEF_POST_RESP";
export const PROJECT_BRIEF_DELETE_RESP="PROJECT_BRIEF_DELETE_RESP";

//LAYOUT AND UTILS
export const LOADING="LOADING";
export const SERVER_ERROR="SERVER_ERROR";
export const HIDE_ERROR_MODAL="HIDE_ERROR_MODAL";
export const HIDE_SERVERSTATUS_MODAL="HIDE_SERVERSTATUS_MODAL";
export const HIDE_PROJECT_SIDEBAR="HIDE_PROJECT_SIDEBAR";
export const HIDE_RESOURCES_SIDEBAR="HIDE_PROJECT_SIDEBAR";
export const SHOW_PROJECT_SIDEBAR="SHOW_PROJECT_SIDEBAR";
export const SHOW_RESOURCES_SIDEBAR="SHOW_RESOURCES_SIDEBAR";
export const HIDE_LOADER="HIDE_LOADER";

